# Generated by Django 4.0.3 on 2022-11-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_empoly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empoly',
            name='Emp_contact',
            field=models.IntegerField(),
        ),
    ]
