# Generated by Django 4.0.3 on 2022-11-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_subscribe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='empoly',
            name='Emp_photo',
            field=models.ImageField(default=None, null=True, upload_to='empoly_img'),
        ),
    ]
