# Generated by Django 4.0.3 on 2022-11-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_empoly_emp_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empoly',
            name='Emp_photo',
            field=models.ImageField(default=None, null=True, upload_to='img/empoly_img'),
        ),
    ]
