# Generated by Django 4.0.3 on 2022-11-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_empoly_emp_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='name',
            new_name='s_email',
        ),
        migrations.AlterField(
            model_name='empoly',
            name='Emp_photo',
            field=models.ImageField(default=None, null=True, upload_to='empoly_img'),
        ),
    ]
