# Generated by Django 4.0.3 on 2022-11-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_contact_clint_email_alter_contact_clint_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clint_name', models.CharField(max_length=50)),
                ('clint_photo', models.ImageField(default=None, null=True, upload_to='clint_img')),
                ('company_name', models.CharField(max_length=50)),
                ('reviw', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
