# Generated by Django 4.0.3 on 2022-11-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
