# Generated by Django 4.0.3 on 2022-11-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='author_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='blog_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
