# Generated by Django 4.0.3 on 2022-11-11 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_post_author_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='author_image',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='blog_image',
        ),
    ]
