# Generated by Django 4.0.3 on 2022-11-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_post_author_image_blog_post_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='author_image',
            field=models.ImageField(default=None, null=True, upload_to='img/author_image'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='blog_image',
            field=models.ImageField(default=None, null=True, upload_to='img/blog_image'),
        ),
    ]
