# Generated by Django 4.0.3 on 2022-11-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_post_author_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='author_image',
            field=models.ImageField(default=None, null=True, upload_to='author_image'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='blog_image',
            field=models.ImageField(default=None, null=True, upload_to='blog_image'),
        ),
    ]
